
version: '3'
services:
  node:
    image: node:17-alpine
    command: sh -c "npm install && npm run dev"
    working_dir: /usr/src/app
    volumes:
      - ./src:/usr/src/app
    ports:
      - "3001:3000"
